version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data   # Mapping a local directory to store SQLite database file
    environment:
      - PYTHONUNBUFFERED=1
