version: '3.9'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - app_data:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=sqlite:///./app/test.db
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
      - RABBITMQ_QUEUE=myqueue
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3.12.14-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    command: >
      sh -c "
        rabbitmq-server &
        sleep 10 &&
        rabbitmqctl list_users | grep myuser || rabbitmqctl add_user myuser mypassword &&
        rabbitmqctl set_user_tags myuser administrator &&
        rabbitmqctl set_permissions -p / myuser '.*' '.*' '.*' &&
        rabbitmqctl delete_user guest &&
        rabbitmqctl stop &&
        rabbitmq-server
      "

  gateway:
    image: nginx:alpine
    ports:
      - "8000:80"
    depends_on:
      app:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  app_data:
