version: '3.8'

services:
  user-service:
    build: ./service_user
    ports:
      - "8000:8000"
    volumes:
      - ./service_user/app:/app/app
    environment:
      - DATABASE_URL=sqlite:///./test.db

  log-service:
    build: ./service_log
    ports:
      - "8001:8000"
    volumes:
      - ./service_log/app:/app/app
    environment:
      - DATABASE_URL=sqlite:///./test.db

  image-processing-service:
    build: ./service_image_processing
    ports:
      - "8002:8000"
    volumes:
      - ./service_image_processing/app:/app/app
    environment:
      - DATABASE_URL=sqlite:///./test.db

networks:
  default:
    driver: bridge
