version: '3.9'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./test.db:/app/test.db
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3.12.14-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

